name: starwars_app
description: An example graphql_flutter application utilizing graphql_starwars_test_server

publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql: ^5.0.0
  graphql_flutter: ^5.0.0
  universal_platform:
    ^0.1.3
    # https://github.com/flutter/flutter/issues/36126#issuecomment-596215587

flutter:
  uses-material-design: true

